---
filename: s3_config_files.yaml
enabled: true
meta:
  name: S3 Configuration Files
  author: PaperMtn
  date: '2021-09-24'
  description: Detects exposed S3 configuration files
  severity: '70'
tombstone: false
scope:
- files
- drafts
file_types:
locations:
  - public
  - private
  - connect
  - im
  - mpim
test_cases:
  match_cases:
  - secret_key = 123456789abcdefg123456789123456789
  fail_cases:
  - secret_key = $S3_SECRET_KEY
search_strings:
- 's3cfg'
- 's3cmd.ini'
pattern: '(?i)(''|"){0,2}secret_key(''|"){0,2} = (''|"){0,2}([0-9a-zA-Z!@#$&()\/\-`_.+,"]{20,})(''|"){0,2}'
